### ISSUE TITLE
tex: Section 3.4. Gaussian pseudo-likelihood is wrong paragraph

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#22]
@mjvakili : Can you take a look at the paragraph in Section 3.4. that reiterates how Gaussian pseudo-likelihood is wrong? Close this if you think it's fine.

**Comment by mjvakili** [comment]
@changhoonhahn : https://github.com/mjvakili/ccppabc/blob/master/ccppabc/text/revision/main.tex#L991
I share your intuition that GMF shouldn't be Gaussian distributed. It should be Poissoin because it's essentially a histogram. But saying that Gaussian likelihood ***clearly misrepresents*** might require another sentence that add justification or some explanation for this claim.

**Comment by mjvakili** [comment]
Great. I'm closing this now.
